### ISSUE TITLE
Summernote editor doesn't work correctly after update

### ISSUE THREAD

**Issue by Imerion** [robiso/summernote-editor#8] opened 2022-01-31 12:44 UTC
After updating to the new version of summernote-editor it no longer seems to work correctly. I have tried this for 3.2, 3.2.1 and 3.2.2 on two different pages and in both cases many of the buttons have stopped working and the toolbar looks like there are extra arrows here and there. The main problem seems to be that no drop-downs appear, so adding tables or chosing a style is broken. No idea what could be causing this. Both pages I tested have some custom code, but the previous version of summernote editor worked fine. If I can help with any more information just tell me and I will see what I can provide!

Here is how the toolbar currently looks:
![Toolbar](https://user-images.githubusercontent.com/16926509/151795726-c39eec7d-3db9-4223-b0fe-039929f4353c.png)

**Comment by robiso** [comment] 2022-01-31 12:47
@Imerion 
1. What version of WonderCMS are you using?
2. Is there any specific theme you are using?

**Comment by Imerion** [comment] 2022-01-31 13:02
This happened with both WoncerCMS 3.3.0 and 3.2.0. Using the old version of the summernote editor plugin worked fine with both new releases though. The problem appeared first when I updated the plugin.

Both pages use the Parallax theme.

**Comment by robiso** [comment] 2022-02-01 05:55
I've updated both the Parallax theme and the Summernote editor to fix this globally.
Update both and it should work as expected. (Update should land within the next 24 hours).
- Summernote 3.2.3
- Parallax 3.2.2

Closing issue for now, please reopen this issue if any problems persist.

**Closed as completed by robiso** 2022-02-01 05:55 UTC

**Comment by Imerion** [comment] 2022-02-01 14:54
That solved the problem! Thanks a lot!

**Comment by robiso** [comment] 2022-02-01 15:59
Most welcome, glad it helped :)

**Comment by Imerion** [comment] 2022-02-21 18:59
Sorry for commenting on a closed issue, but the bug seems to affect the LightBlue theme as well. I got the same result on another page after updating.

**Comment by robiso** [comment] 2022-02-26 19:23
@Imerion this seems to be affecting all themes that have jQuery by default, as Summernote also uses jQuery.

I would like to avoid all themes using jQuery, however I pushed an update to the lightBlue theme.

The fix was hiding the theme jQuery if the admin is logged in.
Changing
`<script src='https://code.jquery.com/jquery-1.12.4.min.js' integrity='sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ' crossorigin='anonymous'></script>`

To. 
```
<?php
	if(!$Wcms->loggedIn) {
		echo "<script src='https://code.jquery.com/jquery-1.12.4.min.js' integrity='sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ' crossorigin='anonymous'></script>";
	}
?>
```
did the trick. Happy updating :)

**Comment by Imerion** [comment] 2022-02-26 21:28
Thanks! Hopefully I won't have to do this with any more of the older themes.

**Comment by hosios** [comment] 2022-04-07 02:06
Hi, 

just wanted to confirm, I'm using the Dark Blue theme and had the same problem. And it was driving me crazy. But  Ijust aplyed the fix mentioned by @robiso and it worked. 

Thank you,

**Comment by Jim-Young** [comment] 2022-09-27 05:06
I can confirm that paper L use jquery and the fix worked for me.
